-- AlterTable
ALTER TABLE `users` ADD COLUMN `installmentsPaid` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `installmentsRequired` INTEGER NOT NULL DEFAULT 1,
    MODIFY `subscriptionStatus` ENUM('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'INCOMPLETE', 'LIFETIME_ACCESS') NOT NULL DEFAULT 'INCOMPLETE';
